FROM alpine:3.13

RUN apk add --no-cache \
  curl \
  dnsmasq \
  hostapd \
  resolvconf \
  tzdata

RUN curl -fsSL https://install.pi-hole.net | bash

RUN echo "nameserver 127.0.0.1" >> /etc/resolvconf/resolv.conf.d/base

EXPOSE 53/tcp
EXPOSE 53/udp

CMD ["/usr/sbin/pihole-FTL"]